spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: development
  jpa:
    database-platform: com.mysql.cj.jdbc.Driver
    hibernate:
      ddl-auto: validate