spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdbfile:./target/db
    driver-class-name: org.h2.Driver
    username: root
    password: asdf
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console