spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: development
  jpa:
    database-platform: org.hibernate.dialect.MySQLMyISAMDialect
    hibernate:
      ddl-auto: validate