openapi: 3.0.1

info:
  title: SpringAngularTemplate API
  version: 1.0.0

servers:
  - url: https://localhost:8080
  - url: http://localhost:8080

paths:
  /test/message:
    get:
      tags:
        - test
      summary: Requests the welcome message
      operationId: welcomeMessage
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: 'dto/test.yaml#/testDto'
